/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-My_React_Project-rZ7doMYqNHRo2cYO2IL8KyMC8UySgm03",
  "version": "2020-11-20"
}

export default ebconfig;